### ISSUE TITLE
Sortable not working in internet explorer 10(IE10)

### ISSUE THREAD

**Issue by giri-jeedigunta** [rkusa/touch-dnd#42]
The sortable example on this page http://ma.rkusa.st/touch-dnd/sortable.html is not working as expected on IE10. Is there a work around for this? Please advise.

**Comment by rkusa** [comment]
Should be fixed (in master; ma.rkusa.st/touch-dnd ist not yet updated)
Thanks for reporting!

**Comment by giri-jeedigunta** [comment]
Thank you for the quick response. I took the latest JS and tested it locally but the sortable is still not working. Here is a little more detail on the issue that I'm facing. I'm able to drag an item seamlessly but when I try to drop it at a desired position it doesn't work.

**Comment by rkusa** [comment]
Thanks for testing it. I'll have a look tomorrow

**Comment by rkusa** [comment]
I tried it (with W8 + IE 10.0.29) again and had no problems. I've update http://ma.rkusa.st/touch-dnd to the current version. Would you mind having a look again?
Thanks

**Comment by giri-jeedigunta** [comment]
I have tested the demo page on Win7 IE10 and it works perfectly. Thanks for this wonderful plugin and quick turn around on this issue. Appreciate it.
